// Déclaration du tableau contenant la liste des mots proposés à l'utilisateur
const listeMots = [
  "Alphabet",
  "Cultutre",
  "Reblochon",
  "Mémoire",
  "Rhododendron",
  "Ordinateur",
  "Parallèle",
  "Programmation",
  "Souris",
  "Méditerranée",
  "Téléphone",
  "Dilemme",
  "Vidéo",
  "Web",
  "Zéro",
  "Cirrhose",
  "Défaut",
  "Erreur",
  "Synonyme",
  "Antonyme",
];

const listePhrases = [
  "La Bohême !",
  "Vers l'infini et au delà",
  "La vie est un long fleuve agité",
  "Le reblochon est un fromage",
  "Après la pluie, le beau temps",
  "La programmation c'est la vie",
  "La souris est dans le fromage",
  "Le téléphone sonne toujours deux fois",
  "La vidéo tue la radio",
  "Le web c'est la vie",
  "Zéro défaut",
  "La cirrhose n'est pas une maladie",
  "L'erreur est humaine",
  "Trouver un synonyme n'est pas un antonyme",
  "La méditerranée est une mer",
  "Le rhododendron est une fleur",
  "La culture c'est l'ouverture",
  "L'ordinateur est un outil",
  "La programmation est un art",
  "La mémoire est un don",
];
